# Generated by Django 4.2.11 on 2024-05-27 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Waiter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "charge",
                    models.CharField(
                        choices=[
                            ("MG", "MANAGER"),
                            ("AT", "ADMINTABLES"),
                            ("EX", "EXTRA"),
                        ],
                        default="MG",
                        max_length=60,
                    ),
                ),
            ],
        ),
    ]
