# Generated by Django 4.2.11 on 2024-05-27 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_waiter_user"),
        ("restaurant", "0002_shift"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shift",
            name="restaurant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="restaurant.restaurant",
            ),
        ),
        migrations.AlterField(
            model_name="shift",
            name="waiter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="users.waiter"
            ),
        ),
        migrations.CreateModel(
            name="Tip_Waiter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("paid", models.BooleanField()),
                (
                    "bill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="restaurant.bill",
                    ),
                ),
                (
                    "waiter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="users.waiter",
                    ),
                ),
            ],
        ),
    ]
